<%@ page language="java" pageEncoding="utf-8"%>
[    
   {
   task:'硬件',
   uiProvider:'col',
   cls:'master-task',
   iconCls:'task-folder',
   children:[{
       task:'001',
       name:'AAA',
       count:'100',
       price1:'10.0',
       price2:'12.0',
       uiProvider:'col',
       leaf:true,
       iconCls:'task'
   },{
       task:'002',
       name:'BBB',
       count:'100',
       price1:'10.0',
       price2:'12.0',
       uiProvider:'col',
       leaf:true,
       iconCls:'task'
   },{
       task:'003',
       name:'CCC',
       count:'100',
       price1:'10.0',
       price2:'12.0',
       uiProvider:'col',
       leaf:true,
       iconCls:'task'
   },{
       task:'004',
       name:'DDD',
       count:'100',
       price1:'10.0',
       price2:'12.0',
       uiProvider:'col',
       leaf:true,
       iconCls:'task'
   },{
       task:'005',
       name:'EEE',
       count:'100',
       price1:'10.0',
       price2:'12.0',
       uiProvider:'col',
       leaf:true,
       iconCls:'task'
   },{
       task:'硬件合计',
       price1:'1000',
       price2:'1200',
       uiProvider:'col',
       leaf:true,
       iconCls:'task'
   }]
},{
   task:'软件',
   uiProvider:'col',
   cls:'master-task',
   iconCls:'task-folder',
   children:[{
       task:'soft01',
       name:'aaa',
       count:'1',
       price1:'100',
       price2:'120',
       uiProvider:'col',
       leaf:true,
       iconCls:'task'
   },{
       task:'soft02',
       name:'bbb',
       count:'1',
       price1:'100',
       price2:'120',
       uiProvider:'col',
       leaf:true,
       iconCls:'task'
   },{
       task:'soft03',
       name:'ccc',
       count:'1',
       price1:'100',
       price2:'120', 
       uiProvider:'col',
       leaf:true,
       iconCls:'task'
   },{
       task:'软件合计',
       price1:'2000',
       price2:'2400', 
       uiProvider:'col',
       leaf:true,
       iconCls:'task'
   }]
},{
   task:'价格合计',
   uiProvider:'col',
   cls:'master-task',
   iconCls:'task-folder',
   price1:'3000',
   price2:'3600',
   children:[]
}
]